### ISSUE TITLE
Issue when creating hostgroup

### ISSUE THREAD

**Issue by bradbeam** [AlekSi/zabbix#10]
When creating a host group using the api.HostGroupsCreate function I get 
```
Error: -32602 (Invalid params.): Cannot set "internal" for host group "my.hosts.all".
```
I think the offending line is https://github.com/AlekSi/zabbix/blob/master/host_group.go#L20 where it needs to be marked as omitempty since it sounds like this might be a readonly field [1] ( but was erroneously noted otherwise if I'm reading the bug details correctly ). If I call the api directly `Api.Call("hostgroup.create", zabbix.Params{"name": hostgroup})` it works fine. 

Using berngp/docker-zabbix container for testing if that helps ( zabbix ui shows 2.4.6 ). 

[1]
https://support.zabbix.com/browse/ZBX-9017

**Comment by AlekSi** [comment]
Thanks!
