### ISSUE TITLE
Missing history support

### ISSUE THREAD

**Issue by errnoh** [AlekSi/zabbix#12]
Everything in the library works really well and it's easy to use. Only thing I'm missing is support for History objects. I wrote a simple version that does what I need, but I don't think it's complete enough to be added to master.

Couple things that need to be considered:
- This version handles all Values as strings. This was trivial to implement since the reflector works great. It would also be quite easy to add version that checks `history` parameter and passes proper struct type to reflector. Problem with this is that it would need to either return `interface{}` (or an actual interface with getters), which is not how rest of the system works and is ugly. Another version would be to have Value as interface{}, in which case it would need to be casted to proper value each time, which is even worse.
- I wrote a test, but since I'm using actual db and not an empty one it doesn't create new History object, thus it would fail on an empty db.

You can see the commit here: https://github.com/errnoh/zabbix/commit/9e6d3a16af0b67faa27ca970bcb45a2e2f09afc0

**Comment by errnoh** [comment]
There's also the possibility of having separate `GetHistoriesFloat()`, `GetHistoriesText()`, etc. That would allow one to have separate return types for each of the different history types.

**Comment by AlekSi** [comment]
See #24.
