### ISSUE TITLE
Zabbix 2.4 apiinfo.version requires unauthenticated call

### ISSUE THREAD

**Issue by bradbeam** [AlekSi/zabbix#8]
https://www.zabbix.com/documentation/2.2/manual/api/reference/apiinfo/version
This method is available to unauthenticated users and should be called without the auth parameter in the JSON-RPC request. Starting from Zabbix 2.4 the method will return an error if the auth parameter is given. 

This is pretty annoying :(.  Anyways, I'm open to working on this but wanted to get some thoughts together on the best way to approach it. I'd like to add an `auth bool` parameter to call.bytes and let it flex on using api.Auth[1], but this would require a slight change to all api methods that have been created. Thoughts?

[1]
``` go
func (api *API) callBytes(method string, params interface{}, auth bool) (b []byte, err error) {
        id := atomic.AddInt32(&api.id, 1)
        if auth {
                jsonobj := request{"2.0", method, params, api.Auth, id}
        } else {
        
                jsonobj := request{"2.0", method, params, "", id}
        }
```

**Comment by AlekSi** [comment]
Thanks for looking into it.
Let me think about it for few days. If I don't reply this week, please ping me.

**Comment by AlekSi** [comment]
Well, that was a _long_ week :confounded:
